In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
 np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([-1.63228233,  0.77918332,  0.04512784,  2.0098005 , -0.10939388,
       -0.68836771,  0.09797297, -0.53387695,  0.5904974 ,  0.0502056 ])

In [7]:
B = np.random.randn(10)

In [8]:
B

array([-0.17315282,  0.27830508, -0.46323713,  0.0523114 , -0.43675347,
       -0.06894522, -0.17048857,  1.71171978,  0.01223328,  0.30832568])

In [9]:
np.add(A,B)

array([-1.80543515,  1.05748841, -0.41810929,  2.06211189, -0.54614736,
       -0.75731293, -0.0725156 ,  1.17784284,  0.60273067,  0.35853128])

In [10]:
np.maximum(A,B)

array([-0.17315282,  0.77918332,  0.04512784,  2.0098005 , -0.10939388,
       -0.06894522,  0.09797297,  1.71171978,  0.5904974 ,  0.30832568])

In [11]:
import webbrowser

In [14]:
website = 'http://www.google.com'

In [15]:
webbrowser.open(website)

True