In [1]:
import numpy as np

In [2]:
my_list1 = [1, 2, 3, 4]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
 my_list2 = [11, 22, 33, 44]

In [6]:
my_lists = [my_list1,my_list2]

In [7]:
my_array2 = np.array(my_lists)

In [8]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [9]:
my_array2.shape

(2, 4)

In [10]:
my_array2.dtype

dtype('int32')

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
my_zeros_array = np.zeros(5)

In [13]:
my_zeros_array.dtype

dtype('float64')

In [14]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
ones = np.ones([5,5])

In [18]:
ones.shape

(5, 5)

In [21]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(2, 1022, 3)

array([   2,    5,    8,   11,   14,   17,   20,   23,   26,   29,   32,
         35,   38,   41,   44,   47,   50,   53,   56,   59,   62,   65,
         68,   71,   74,   77,   80,   83,   86,   89,   92,   95,   98,
        101,  104,  107,  110,  113,  116,  119,  122,  125,  128,  131,
        134,  137,  140,  143,  146,  149,  152,  155,  158,  161,  164,
        167,  170,  173,  176,  179,  182,  185,  188,  191,  194,  197,
        200,  203,  206,  209,  212,  215,  218,  221,  224,  227,  230,
        233,  236,  239,  242,  245,  248,  251,  254,  257,  260,  263,
        266,  269,  272,  275,  278,  281,  284,  287,  290,  293,  296,
        299,  302,  305,  308,  311,  314,  317,  320,  323,  326,  329,
        332,  335,  338,  341,  344,  347,  350,  353,  356,  359,  362,
        365,  368,  371,  374,  377,  380,  383,  386,  389,  392,  395,
        398,  401,  404,  407,  410,  413,  416,  419,  422,  425,  428,
        431,  434,  437,  440,  443,  446,  449,  4