In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr = np.arange(9).reshape(3,3)

In [3]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr,arr],axis=1
              )

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr,arr],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# concetenate in pandas

In [7]:
ser1 = Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [12]:
pd.concat([ser1,ser2],sort=False)

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [13]:
pd.concat([ser1,ser2],axis=1)   #produces a dataframe

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [14]:
#ADDING MARKERS OR KEYS TO THE SERIES.
#using index hierachy

In [15]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [16]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [17]:
dframe1

X         Y         Z
0 -0.367664 -0.568013 -0.345383
1 -0.906956  1.683697 -0.952356
2 -0.637995 -1.356338  1.093090
3  0.123453  1.947135  0.469638

In [18]:
dframe2

Y         Q         X
0 -0.213429 -1.564479 -0.632870
1 -1.520682 -2.134793  0.724575
2 -0.124480  0.068149 -0.747986

In [19]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0 -0.367664 -0.568013 -0.345383       NaN
1 -0.906956  1.683697 -0.952356       NaN
2 -0.637995 -1.356338  1.093090       NaN
3  0.123453  1.947135  0.469638       NaN
0 -0.632870 -0.213429       NaN -1.564479
1  0.724575 -1.520682       NaN -2.134793
2 -0.747986 -0.124480       NaN  0.068149

In [20]:
pd.concat([dframe1,dframe2],ignore_index=True)

X         Y         Z         Q
0 -0.367664 -0.568013 -0.345383       NaN
1 -0.906956  1.683697 -0.952356       NaN
2 -0.637995 -1.356338  1.093090       NaN
3  0.123453  1.947135  0.469638       NaN
4 -0.632870 -0.213429       NaN -1.564479
5  0.724575 -1.520682       NaN -2.134793
6 -0.747986 -0.124480       NaN  0.068149

In [21]:
#check out more information and documentation